# coding: utf-8

"""
    Allegro REST API

    https://developer.allegro.pl/about  # noqa: E501

    OpenAPI spec version: latest
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest

import openapi_client
from openapi_client.models.available_constraint import AvailableConstraint  # noqa: E501
from openapi_client.rest import ApiException


class TestAvailableConstraint(unittest.TestCase):
    """AvailableConstraint unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testAvailableConstraint(self):
        """Test AvailableConstraint"""
        # FIXME: construct object with mandatory attributes with example values
        # model = openapi_client.models.available_constraint.AvailableConstraint()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
