# coding: utf-8

"""
    Allegro REST API

    https://developer.allegro.pl/about  # noqa: E501

    OpenAPI spec version: latest
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest

import openapi_client
from openapi_client.models.seller_rebate_dto import SellerRebateDto  # noqa: E501
from openapi_client.rest import ApiException


class TestSellerRebateDto(unittest.TestCase):
    """SellerRebateDto unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testSellerRebateDto(self):
        """Test SellerRebateDto"""
        # FIXME: construct object with mandatory attributes with example values
        # model = openapi_client.models.seller_rebate_dto.SellerRebateDto()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
