# coding: utf-8

"""
    Allegro REST API

    https://developer.allegro.pl/about  # noqa: E501

    OpenAPI spec version: latest
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest

import openapi_client
from openapi_client.models.constraint_criteria import ConstraintCriteria  # noqa: E501
from openapi_client.rest import ApiException


class TestConstraintCriteria(unittest.TestCase):
    """ConstraintCriteria unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testConstraintCriteria(self):
        """Test ConstraintCriteria"""
        # FIXME: construct object with mandatory attributes with example values
        # model = openapi_client.models.constraint_criteria.ConstraintCriteria()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
