# coding: utf-8

"""
    Allegro REST API

    https://developer.allegro.pl/about  # noqa: E501

    OpenAPI spec version: latest
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest

import openapi_client
from openapi_client.api.size_tables_api import SizeTablesApi  # noqa: E501
from openapi_client.rest import ApiException


class TestSizeTablesApi(unittest.TestCase):
    """SizeTablesApi unit test stubs"""

    def setUp(self):
        self.api = openapi_client.api.size_tables_api.SizeTablesApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_get_table_using_get(self):
        """Test case for get_table_using_get

        Get a size table details  # noqa: E501
        """
        pass

    def test_get_tables_using_get(self):
        """Test case for get_tables_using_get

        Get the user's size tables  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
