# coding: utf-8

"""
    Allegro REST API

    https://developer.allegro.pl/about  # noqa: E501

    OpenAPI spec version: latest
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest

import openapi_client
from openapi_client.models.order_events_list import OrderEventsList  # noqa: E501
from openapi_client.rest import ApiException


class TestOrderEventsList(unittest.TestCase):
    """OrderEventsList unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testOrderEventsList(self):
        """Test OrderEventsList"""
        # FIXME: construct object with mandatory attributes with example values
        # model = openapi_client.models.order_events_list.OrderEventsList()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
