# coding: utf-8

"""
    Allegro REST API

    https://developer.allegro.pl/about  # noqa: E501

    OpenAPI spec version: latest
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest

import openapi_client
from openapi_client.models.full_definition_response import FullDefinitionResponse  # noqa: E501
from openapi_client.rest import ApiException


class TestFullDefinitionResponse(unittest.TestCase):
    """FullDefinitionResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testFullDefinitionResponse(self):
        """Test FullDefinitionResponse"""
        # FIXME: construct object with mandatory attributes with example values
        # model = openapi_client.models.full_definition_response.FullDefinitionResponse()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
